<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>SeaQRS</PackageId>
    <Authors>YOUR_NAME</Authors>
    <Description>A lightweight CQRS library for .NET that provides strongly-typed commands and queries with delegate-based dependency injection.</Description>
    <PackageTags>cqrs;commands;queries;di</PackageTags>
    <RepositoryUrl>https://github.com/YOUR_USERNAME/SeaQRS</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>


  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>

</Project>
